
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Feb  6 2023 10:00:23 IST (Feb  6 2023 04:30:23 UTC)

// Verification Directory fv/csaa 

module csaa(sum, cout, a, b, d);
  input [7:0] a, b, d;
  output [8:0] sum;
  output cout;
  wire [7:0] a, b, d;
  wire [8:0] sum;
  wire cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_18, n_20, n_22, n_24, n_26, n_28;
  ADDHXL g1042__8780(.A (n_4), .B (n_28), .CO (cout), .S (sum[8]));
  ADDFX1 g1043__4296(.A (n_5), .B (n_12), .CI (n_26), .CO (n_28), .S
       (sum[7]));
  ADDFX1 g1044__3772(.A (n_13), .B (n_8), .CI (n_24), .CO (n_26), .S
       (sum[6]));
  ADDFX1 g1045__1474(.A (n_9), .B (n_2), .CI (n_22), .CO (n_24), .S
       (sum[5]));
  ADDFX1 g1046__4547(.A (n_3), .B (n_0), .CI (n_20), .CO (n_22), .S
       (sum[4]));
  ADDFX1 g1047__9682(.A (n_1), .B (n_6), .CI (n_18), .CO (n_20), .S
       (sum[3]));
  ADDFX1 g1048__2683(.A (n_7), .B (n_10), .CI (n_16), .CO (n_18), .S
       (sum[2]));
  ADDHXL g1049__1309(.A (n_14), .B (n_11), .CO (n_16), .S (sum[1]));
  ADDFX1 g1051__6877(.A (b[0]), .B (a[0]), .CI (d[0]), .CO (n_14), .S
       (sum[0]));
  ADDFX1 g1050__2900(.A (b[6]), .B (a[6]), .CI (d[6]), .CO (n_12), .S
       (n_13));
  ADDFX1 g1053__2391(.A (b[1]), .B (a[1]), .CI (d[1]), .CO (n_10), .S
       (n_11));
  ADDFX1 g1056__7675(.A (b[5]), .B (a[5]), .CI (d[5]), .CO (n_8), .S
       (n_9));
  ADDFX1 g1055__7118(.A (b[2]), .B (a[2]), .CI (d[2]), .CO (n_6), .S
       (n_7));
  ADDFX1 g1057__8757(.A (b[7]), .B (a[7]), .CI (d[7]), .CO (n_4), .S
       (n_5));
  ADDFX1 g1052__1786(.A (b[4]), .B (a[4]), .CI (d[4]), .CO (n_2), .S
       (n_3));
  ADDFX1 g1054__5953(.A (b[3]), .B (a[3]), .CI (d[3]), .CO (n_0), .S
       (n_1));
endmodule

