
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jan 25 2023 10:04:10 IST (Jan 25 2023 04:34:10 UTC)

// Verification Directory fv/T_ff 

module T_ff(t, clk, reset, q, q_bar);
  input t, clk, reset;
  output q, q_bar;
  wire t, clk, reset;
  wire q, q_bar;
  wire n_0, n_1, n_2, n_3;
  DFFQX1 q_bar_reg(.CK (clk), .D (n_3), .Q (q_bar));
  DFFQX1 q_reg(.CK (clk), .D (n_2), .Q (q));
  NAND2BXL g87__8780(.AN (reset), .B (n_0), .Y (n_3));
  NOR2XL g88__4296(.A (reset), .B (n_1), .Y (n_2));
  XNOR2XL g90__3772(.A (t), .B (q), .Y (n_1));
  XNOR2XL g89__1474(.A (t), .B (q_bar), .Y (n_0));
endmodule

