
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Feb  8 2023 13:07:58 IST (Feb  8 2023 07:37:58 UTC)

// Verification Directory fv/bcd8 

module bcd8(sum, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] sum;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] sum;
  wire cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_14, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_25, n_26, n_27, n_28;
  CLKXOR2X1 g732__8780(.A (n_23), .B (n_27), .Y (sum[7]));
  CLKXOR2X1 g731__4296(.A (n_28), .B (n_20), .Y (sum[6]));
  AO21X1 g733__3772(.A0 (n_25), .A1 (n_26), .B0 (n_28), .Y (sum[5]));
  NOR2XL g734__1474(.A (n_22), .B (n_26), .Y (n_27));
  NOR2XL g735__4547(.A (n_25), .B (n_26), .Y (n_28));
  NOR2XL g736__9682(.A (n_21), .B (cout), .Y (n_26));
  NOR2BXL g737__2683(.AN (n_23), .B (n_22), .Y (cout));
  ADDFX1 g738__1309(.A (b[7]), .B (a[7]), .CI (n_19), .CO (n_21), .S
       (n_23));
  NOR2XL g739__6877(.A (n_25), .B (n_20), .Y (n_22));
  ADDFX1 g740__2900(.A (b[6]), .B (a[6]), .CI (n_18), .CO (n_19), .S
       (n_20));
  ADDFX1 g741__2391(.A (b[5]), .B (a[5]), .CI (n_14), .CO (n_18), .S
       (n_25));
  CLKXOR2X1 g743__7675(.A (n_7), .B (n_9), .Y (sum[3]));
  CLKXOR2X1 g742__7118(.A (n_12), .B (n_4), .Y (sum[2]));
  ADDFX1 g744__8757(.A (b[4]), .B (a[4]), .CI (n_8), .CO (n_14), .S
       (sum[4]));
  AO21X1 g745__1786(.A0 (n_11), .A1 (n_10), .B0 (n_12), .Y (sum[1]));
  NOR2XL g746__5953(.A (n_11), .B (n_10), .Y (n_12));
  NOR2XL g747__5703(.A (n_6), .B (n_10), .Y (n_9));
  NOR2XL g748__7114(.A (n_5), .B (n_8), .Y (n_10));
  NOR2BXL g749__5266(.AN (n_7), .B (n_6), .Y (n_8));
  ADDFX1 g750__2250(.A (b[3]), .B (a[3]), .CI (n_3), .CO (n_5), .S
       (n_7));
  NOR2XL g751__6083(.A (n_11), .B (n_4), .Y (n_6));
  ADDFX1 g752__2703(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_3), .S
       (n_4));
  ADDFX1 g753__5795(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (n_11));
  ADDFX1 g754__7344(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_0), .S
       (sum[0]));
endmodule

