
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jan 23 2023 11:13:33 IST (Jan 23 2023 05:43:33 UTC)

// Verification Directory fv/Dff 

module Dff(D, clk, sync_reset, Q);
  input D, clk, sync_reset;
  output Q;
  wire D, clk, sync_reset;
  wire Q;
  wire n_0;
  DFFQXL Q_reg(.CK (clk), .D (n_0), .Q (Q));
  NOR2BXL g4__8780(.AN (D), .B (sync_reset), .Y (n_0));
endmodule

