
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Feb  2 2023 08:26:48 IST (Feb  2 2023 02:56:48 UTC)

// Verification Directory fv/ripple 

module ripple(a, b, d, s, o);
  input [3:0] a, b;
  input d;
  output [3:0] s;
  output o;
  wire [3:0] a, b;
  wire d;
  wire [3:0] s;
  wire o;
  wire n_0, n_2, n_4;
  ADDFXL g259__8780(.A (a[3]), .B (b[3]), .CI (n_4), .CO (o), .S
       (s[3]));
  ADDFX1 g260__4296(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_4), .S
       (s[2]));
  ADDFX1 g261__3772(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (s[1]));
  ADDFX1 g262__1474(.A (b[0]), .B (a[0]), .CI (d), .CO (n_0), .S
       (s[0]));
endmodule

