
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jan 23 2023 11:58:56 IST (Jan 23 2023 06:28:56 UTC)

// Verification Directory fv/jkff 

module jkff(J, K, clk, sync_reset, Q, Qnot);
  input J, K, clk, sync_reset;
  output Q, Qnot;
  wire J, K, clk, sync_reset;
  wire Q, Qnot;
  wire n_0, n_2, n_3;
  DFFQX1 Q_reg(.CK (clk), .D (n_3), .Q (Q));
  NOR2XL g99__8780(.A (sync_reset), .B (n_2), .Y (n_3));
  AOI22X1 g100__4296(.A0 (n_0), .A1 (Q), .B0 (J), .B1 (Qnot), .Y (n_2));
  CLKINVX1 g102(.A (Q), .Y (Qnot));
  INVXL g101(.A (K), .Y (n_0));
endmodule

