
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Apr 18 2023 10:20:22 IST (Apr 18 2023 04:50:22 UTC)

// Verification Directory fv/sub 

module sub(s, cb, a, b);
  input [3:0] a, b;
  output [3:0] s;
  output cb;
  wire [3:0] a, b;
  wire [3:0] s;
  wire cb;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_21, n_22;
  assign cb = 1'b0;
  OAI221XL g529__8780(.A0 (n_22), .A1 (n_21), .B0 (n_14), .B1 (n_11),
       .C0 (n_12), .Y (s[3]));
  CLKXOR2X1 g530__4296(.A (n_22), .B (n_21), .Y (s[2]));
  OAI21XL g531__3772(.A0 (n_19), .A1 (n_18), .B0 (n_17), .Y (s[1]));
  NAND2BXL g532__1474(.AN (n_19), .B (n_18), .Y (n_21));
  NAND2XL g533__4547(.A (n_18), .B (n_19), .Y (n_17));
  AOI21XL g534__9682(.A0 (b[1]), .A1 (n_15), .B0 (n_16), .Y (n_19));
  NOR2XL g535__2683(.A (b[1]), .B (n_15), .Y (n_16));
  MXI2XL g536__1309(.A (n_14), .B (n_13), .S0 (n_6), .Y (n_15));
  MXI2XL g537__6877(.A (n_13), .B (n_14), .S0 (n_9), .Y (n_22));
  NAND2XL g538__2900(.A (n_14), .B (n_11), .Y (n_12));
  NOR2XL g539__2391(.A (s[0]), .B (n_14), .Y (n_18));
  INVXL g540(.A (n_14), .Y (n_13));
  ADDFX1 g541__7675(.A (n_1), .B (a[3]), .CI (n_8), .CO (n_14), .S
       (n_11));
  ADDFX1 g542__7118(.A (n_0), .B (a[2]), .CI (n_7), .CO (n_8), .S
       (n_9));
  OAI21XL g543__8757(.A0 (n_4), .A1 (b[1]), .B0 (n_5), .Y (n_7));
  NOR2BXL g544__1786(.AN (n_5), .B (n_4), .Y (n_6));
  NOR2XL g545__5953(.A (a[1]), .B (n_3), .Y (n_4));
  NAND2XL g546__5703(.A (a[1]), .B (n_3), .Y (n_5));
  OAI21XL g547__7114(.A0 (n_2), .A1 (b[0]), .B0 (n_3), .Y (s[0]));
  NAND2XL g548__5266(.A (b[0]), .B (n_2), .Y (n_3));
  INVXL g549(.A (a[0]), .Y (n_2));
  INVXL g550(.A (b[3]), .Y (n_1));
  INVXL g551(.A (b[2]), .Y (n_0));
endmodule

