
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Apr 18 2023 10:36:44 IST (Apr 18 2023 05:06:44 UTC)

// Verification Directory fv/enc83 

module enc83(y, x);
  input [7:0] x;
  output [2:0] y;
  wire [7:0] x;
  wire [2:0] y;
  OR4XL g106__8780(.A (x[4]), .B (x[6]), .C (x[5]), .D (x[7]), .Y
       (y[2]));
  OR4XL g107__4296(.A (x[2]), .B (x[3]), .C (x[6]), .D (x[7]), .Y
       (y[1]));
  OR4XL g108__3772(.A (x[1]), .B (x[3]), .C (x[5]), .D (x[7]), .Y
       (y[0]));
endmodule

