
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Feb  7 2023 12:54:10 IST (Feb  7 2023 07:24:10 UTC)

// Verification Directory fv/cska 

module cska(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire n_0, n_1, n_2, n_4, n_6, n_8, n_10, n_12;
  wire n_14, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_26;
  NAND2BXL g668__8780(.AN (cin), .B (n_26), .Y (cout));
  NAND4XL g669__4296(.A (n_8), .B (n_10), .C (n_12), .D (n_22), .Y
       (n_26));
  OAI21XL g670__3772(.A0 (n_23), .A1 (b[7]), .B0 (n_24), .Y (s[7]));
  NAND2XL g671__1474(.A (b[7]), .B (n_23), .Y (n_24));
  AND3XL g673__4547(.A (n_4), .B (n_6), .C (n_21), .Y (n_22));
  OAI211XL g672__9682(.A0 (n_19), .A1 (a[7]), .B0 (n_2), .C0 (n_20), .Y
       (n_23));
  NAND2XL g674__2683(.A (n_17), .B (n_20), .Y (n_21));
  AOI21XL g675__1309(.A0 (n_1), .A1 (n_14), .B0 (n_18), .Y (n_19));
  NAND3BXL g677__6877(.AN (n_18), .B (a[7]), .C (n_16), .Y (n_20));
  NAND3BXL g678__2900(.AN (n_18), .B (b[7]), .C (n_16), .Y (n_17));
  CLKXOR2X1 g676__2391(.A (n_0), .B (n_16), .Y (s[6]));
  INVXL g679(.A (n_16), .Y (n_14));
  ADDFX1 g680__7675(.A (b[5]), .B (a[5]), .CI (n_12), .CO (n_16), .S
       (s[5]));
  ADDFX1 g681__7118(.A (b[4]), .B (a[4]), .CI (n_10), .CO (n_12), .S
       (s[4]));
  ADDFX1 g682__8757(.A (b[3]), .B (a[3]), .CI (n_8), .CO (n_10), .S
       (s[3]));
  ADDFX1 g683__1786(.A (b[2]), .B (a[2]), .CI (n_6), .CO (n_8), .S
       (s[2]));
  ADDFX1 g684__5953(.A (b[1]), .B (a[1]), .CI (n_4), .CO (n_6), .S
       (s[1]));
  ADDFX1 g685__5703(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_4), .S
       (s[0]));
  NAND2BXL g686__7114(.AN (n_1), .B (a[7]), .Y (n_2));
  CLKXOR2X1 g687__5266(.A (b[6]), .B (a[6]), .Y (n_0));
  NOR2XL g688__2250(.A (b[6]), .B (a[6]), .Y (n_18));
  NAND2XL g689__6083(.A (b[6]), .B (a[6]), .Y (n_1));
endmodule

