
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Apr 18 2023 11:09:26 IST (Apr 18 2023 05:39:26 UTC)

// Verification Directory fv/dec38 

module dec38(y, x);
  input [2:0] x;
  output [7:0] y;
  wire [2:0] x;
  wire [7:0] y;
  wire n_0, n_2, n_6, n_8, n_9;
  NOR2XL g152__8780(.A (x[1]), .B (n_8), .Y (y[5]));
  NOR2XL g155__4296(.A (n_9), .B (n_6), .Y (y[6]));
  NOR2XL g153__3772(.A (n_9), .B (n_8), .Y (y[7]));
  NOR2XL g157__1474(.A (x[1]), .B (n_6), .Y (y[4]));
  NOR2XL g158__4547(.A (x[1]), .B (n_2), .Y (y[1]));
  AND2XL g151__9682(.A (x[1]), .B (n_0), .Y (y[2]));
  NOR2XL g156__2683(.A (n_9), .B (n_2), .Y (y[3]));
  NOR2BXL g154__1309(.AN (n_0), .B (x[1]), .Y (y[0]));
  NAND2BXL g162__6877(.AN (x[0]), .B (x[2]), .Y (n_6));
  NAND2XL g159__2900(.A (x[0]), .B (x[2]), .Y (n_8));
  NAND2BXL g161__2391(.AN (x[2]), .B (x[0]), .Y (n_2));
  NOR2XL g160__7675(.A (x[0]), .B (x[2]), .Y (n_0));
  INVXL g163(.A (x[1]), .Y (n_9));
endmodule

