
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jan 20 2023 10:03:41 IST (Jan 20 2023 04:33:41 UTC)

// Verification Directory fv/half 

module half(s, c, a, b, clk);
  input a, b, clk;
  output s, c;
  wire a, b, clk;
  wire s, c;
  wire n_0, n_1;
  DFFQXL s_reg(.CK (clk), .D (n_1), .Q (s));
  DFFQXL c_reg(.CK (clk), .D (n_0), .Q (c));
  ADDHXL g42__8780(.A (b), .B (a), .CO (n_0), .S (n_1));
endmodule

