
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Feb  7 2023 13:18:13 IST (Feb  7 2023 07:48:13 UTC)

// Verification Directory fv/cla 

module cla(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12;
  ADDFXL g593__8780(.A (b[7]), .B (a[7]), .CI (n_12), .CO (cout), .S
       (s[7]));
  ADDFX1 g594__4296(.A (a[6]), .B (b[6]), .CI (n_10), .CO (n_12), .S
       (s[6]));
  ADDFX1 g595__3772(.A (a[5]), .B (b[5]), .CI (n_8), .CO (n_10), .S
       (s[5]));
  ADDFX1 g596__1474(.A (a[4]), .B (b[4]), .CI (n_6), .CO (n_8), .S
       (s[4]));
  ADDFX1 g597__4547(.A (a[3]), .B (b[3]), .CI (n_4), .CO (n_6), .S
       (s[3]));
  ADDFX1 g598__9682(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_4), .S
       (s[2]));
  ADDFX1 g599__2683(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (s[1]));
  ADDFX1 g600__1309(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_0), .S
       (s[0]));
endmodule

